### ISSUE TITLE
Some "reserved keywords" aren't allowed as field names even when unambiguous

### ISSUE THREAD

**Issue by serhalp** [goodeggs/resource-schema#11]
For example, `type` isn't allowed, even though there's no ambiguity with resource-schema's special `type` key for specifying a field's type:

```javascript
{
  "type": String
}
```

There's only one ambiguous case:

```javascript
{
  "events": {
    "type": String
  }
}
```

This can be interpreted as either an `events` field which is a string, or an `events` field with a subfield `type` which is a string.  Mongoose doesn't even support this.  You have to be more explicit:

```javascript
{
  "events": {
    "type": { "type": String }
  }
}
```

We should support the same.  We can figure out whether a key is a field or a special resource-schema keyword by looking at the value.

**Comment by dannynelson** [comment]
Thanks! Resolved in 0.17.2
