### ISSUE TITLE
Installs mongoose as a child dependency

### ISSUE THREAD

**Issue by asalant** [goodeggs/resource-schema#6]
I just noticed that resource-schema installs mongoose as a child dependency in garbanzo:

> kerberos@0.0.7 install /Users/alon/Projects/garbanzo/node_modules/resource-schema/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos

I don't think we want this. It needs to be using the app-level configured instance of mongoose in order to have access to the app's models and the connection. I assume it is written to use the right instance which means this dependency is unnecessary.

Solutions include requiring it as a dev-dependency in the module so that the requiring app has to install mongoose itself. npm dedup could also be a solution. I prefer a solution handled by resource-schema itself rather than being a requirement on the requiring app.

**Comment by makebbekus** [comment]
@asalant Right now mongoose is only used in resource-schema for creating and checking for ObjectId's e.g. `new mongoose.Types.ObjectId()` and `mongoose.Types.ObjectId.isValid()`. You pass in the resource that you want to generate a schema for which is how it currently gets the "right" instance.

@dannynelson and I were just looking at the source code, and we could completely remove mongoose from the source by doing a little more introspection on the passed in model and by using the underlying js-bson library that has ObjectId.

Alternatively, the few mongoose methods used in resource-schema right now have seemingly been in mongoose for a while. We could determine the release and just require a version of mongoose newer than that one but still as a dependency e.g.

```
"dependencies": {
  "mongoose": ">=1.6.2" # or whatever version has the methods that resource-schema is using
```

**Comment by asalant** [comment]
Up to you guys. The last option seems fine and easy.

On Thu, Feb 5, 2015 at 10:48 AM, Michael Kebbekus <notifications@github.com>
wrote:

> @asalant <https://github.com/asalant> Right now mongoose is only used in
> resource-schema for creating and checking for ObjectId's e.g. new
> mongoose.Types.ObjectId() and mongoose.Types.ObjectId.isValid(). You pass
> in the resource that you want to generate a schema for which is how it
> currently gets the "right" instance.
>
> @dannynelson <https://github.com/dannynelson> and I were just looking at
> the source code, and we could completely remove mongoose from the source by
> doing a little more introspection on the passed in model and by using the
> underlying js-bson library that has ObjectId.
>
> Alternatively, the few mongoose methods used in resource-schema right now
> have seemingly been in mongoose for a while. We could determine the release
> and just require a version of mongoose newer than that one but still as a
> dependency e.g.
>
> "dependencies": {
>   "mongoose": ">=1.6.2" # or whatever version has the methods that resource-schema is using
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/goodeggs/resource-schema/issues/6#issuecomment-73102738>
> .
>



-- 
eat well with good eggs on: twitter <http://twitter.com/goodeggs> ||
facebook <http://facebook.com/goodeggs> || blog <http://blog.goodeggs.com/>
